"""Library from SteamPrefill selection and local manifest evidence, never presets."""
import json
import queue
import re
import threading
import time
import urllib.request
from runtime import BASE, atomic_json

PRESET_NAMES={526870:'Satisfactory',1172470:'Apex Legends',1938090:'Call of Duty',714010:'Aimlabs'}

def selection(base=BASE):
    path=base/'prefill/selectedAppsToPrefill.json'
    if not path.exists(): return []
    value=json.loads(path.read_text())
    if not isinstance(value,list) or any(type(i) is not int or not 0<i<2**32 for i in value):
        raise ValueError('Invalid SteamPrefill selection')
    return list(dict.fromkeys(value))

class Catalog:
    def __init__(self, base=BASE):
        self.base=base
        self.path=base/'ui-catalog.json'
        try: self.names=json.loads(self.path.read_text())
        except (OSError,ValueError): self.names={}
        if not isinstance(self.names,dict): self.names={}
        self.pending=set(); self.lock=threading.Lock(); self.queue=queue.Queue()
        threading.Thread(target=self._worker,daemon=True).start()

    def _worker(self):
        while True:
            app=self.queue.get()
            name=PRESET_NAMES.get(app,f'Steam #{app}')
            ok=False
            try:
                req=urllib.request.Request(f'https://store.steampowered.com/api/appdetails?appids={app}&filters=basic&l=english',headers={'User-Agent':'LanternCache/1.0'})
                with urllib.request.urlopen(req,timeout=5) as response:
                    info=json.loads(response.read(2000000))[str(app)]
                if info.get('success') and isinstance(info.get('data',{}).get('name'),str):
                    name=info['data']['name'][:200]; ok=True
            except (OSError,ValueError,KeyError): pass
            with self.lock:
                previous=self.names.get(str(app),{})
                self.names[str(app)]={'name':name if ok else previous.get('name',name),'checkedAt':time.time(),'ok':ok}
                try: atomic_json(self.path,self.names)
                except OSError: pass
                self.pending.discard(app)
            self.queue.task_done()
            time.sleep(.2)

    def games(self, active=False, checking=False, logs=''):
        selected=selection(self.base)
        try: completed=json.loads((self.base/'prefill/successfullyDownloadedDepots.json').read_text())
        except (OSError,ValueError): completed={}
        if not isinstance(completed,dict): completed={}
        # app_containingApp_depot_manifest.bin: generated by SteamPrefill itself.
        evidence={}
        for path in (self.base/'prefill-meta/v1').glob('*.bin'):
            match=re.fullmatch(r'(\d+)_(\d+)_(\d+)_(\d+)\.bin',path.name)
            if not match: continue
            app,_,depot,manifest=match.groups()
            try: stamp=path.stat().st_mtime_ns
            except OSError: continue
            key=(int(app),depot)
            if key not in evidence or stamp>evidence[key][0]: evidence[key]=(stamp,manifest)
        games=[]
        current=None
        # Only the running job's logs can identify an active game.
        if active:
            starts=re.findall(r'Starting (.+)',logs)
            if starts: current=starts[-1].strip()
        failures=set()
        last_name=None
        for line in logs.splitlines():
            start=re.search(r'Starting (.+)',line)
            if start: last_name=start[1].strip().casefold().rstrip('®™')
            if last_name and re.search(r'Unable to download manifests|Unexpected download error|Skipping app',line,re.I):
                failures.add(last_name)
        with self.lock:
            for app in selected:
                info=self.names.get(str(app),{})
                name=info.get('name',PRESET_NAMES.get(app,f'Steam #{app}'))
                ttl=604800 if info.get('ok') else 3600
                if time.time()-info.get('checkedAt',0)>ttl and app not in self.pending:
                    self.pending.add(app); self.queue.put(app)
                manifests={depot:value[1] for (owner,depot),value in evidence.items() if owner==app}
                done=sum(manifest in {str(v) for v in completed.get(depot,[]) if isinstance(v,(str,int))} for depot,manifest in manifests.items() if isinstance(completed.get(depot,[]),list))
                total=len(manifests)
                status='prepared' if total and done==total else 'partial' if done else 'unknown'
                if name.casefold().rstrip('®™') in failures: status='failed'
                if status!='failed' and current and name.casefold().rstrip('®™')==current.casefold().rstrip('®™'):
                    status='checking' if checking else 'downloading'
                games.append({'id':app,'name':name,'genre':'','size':None,'selected':True,
                              'filled':bool(total and done==total),'status':status,
                              'completedDepots':done,'observedDepots':total})
        return games
